version: '3'

services:
  mysql:
    container_name: # 컨테이너 명
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"